---
- name: Update APT Packages
  hosts: all
  become: yes  # This allows the playbook to run with sudo privileges

  tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes
      register: apt_update_result

    - name: Upgrade APT Packages
      apt:
        upgrade: yes
        autoremove: yes
      when: apt_update_result|changed
