---
- name: Disable Apache index.html
  hosts: your_server_hostname
  become: yes
  tasks:
    - name: Disable default Apache index.html
      blockinfile:
        path: /etc/apache2/conf-enabled/localized-defaults.conf  # Path to your Apache configuration file
        block: |
          <Directory /var/www/html>
              Options -Indexes
          </Directory>
