---
- name: Install Apache2 on Ubuntu
  hosts: 192.168.8.171
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
