---
- name: Install MySQL on Ubuntu
  hosts: 192.168.8.171
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install MySQL packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes
