---
- name: Update Ubuntu Server
  hosts: all # Replace with the hostname or IP address of your server
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Perform system upgrade
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
      when: ansible_facts['os_family'] == 'Debian'
