---
- name: Print Hello, World!
  hosts: your_target_host
  become: yes  # This allows the playbook to run with sudo privileges

  tasks:
    - name: Print Hello, World!
      command: echo "Hello, World!"
