---
- name: Reboot All Servers
  hosts: all  # This assumes you have an inventory file that includes all your servers
  become: yes  # Use "yes" to become superuser (usually root) to perform the reboot
  tasks:
    - name: Reboot servers
      reboot:
      async: 0
      poll: 0
