---
- name: Print Hello, World!
  hosts: 10.82.1.207
  become: yes  # This allows the playbook to run with sudo privileges

  tasks:
    - name: Print Hello, World!
      command: echo "Hello, World!"
