---
- name: Create a text file
  hosts: all
  become: yes  # Use 'yes' if you need elevated privileges (sudo)

  tasks:
    - name: Create a text file
      file:
        path: /home/busani/Desktop/file.txt  # Specify the desired path and filename
        state: touch  # This ensures the file is created if it doesn't exist
        owner: busani  # Replace with the desired owner
        group: busani  # Replace with the desired group
        mode: "0644"  # Replace with the desired file permissions

