- name: Create busanis scripts file
  hosts: all  # Assuming you have your server inventory defined in your Ansible configuration
  tasks:
    - name: Create the file
      ansible.builtin.copy:
        content: "{{ lookup('password', '/dev/urandom count=10') | b64encode }}"
        dest: "~/Desktop/busanis_scripts.txt"
