---
- name: Create "busanis scripts" folder on the desktop
  hosts: all
  become: yes  # This is used to escalate privileges, typically using sudo

  tasks:
    - name: Create "busanis scripts" folder
      file:
        path: "{{ lookup('env','HOME') }}/Desktop/busanis scripts"
        state: directory
      delegate_to: "{{ inventory_hostname }}"
