---

-  hosts: all # Replace with the name of your server group or specific host
   become: true  # If your script requires root privileges
   tasks:
     - name: update apt packages
       apt:
           upgrade:yes
           update_cache:yes
