---
- name: Create File on Desktop
  hosts: all
  become: yes  # To run commands with elevated privileges

  tasks:
    - name: Create file on the desktop
      ansible.builtin.copy:
        content: "This is the content of the file."
        dest: "~/Desktop/myfile.txt"
