---
- name: Create 'busanis_scripts' file on desktop
  hosts: all
  become: yes  # Run tasks with sudo/root privileges
  tasks:
    - name: Create 'busanis_scripts' file
      copy:
        content: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=1000') }}"
        dest: "~/busanis_scripts"
        mode: "0644"
